### ISSUE TITLE
Suggestion: Lamborghini Urus

### ISSUE THREAD

**Issue by gabrielcalderon** [PLOKMJNB/FiveM-Civ-Car-Pack#1]
Could you add the Lamborghini Urus? I haven't found one for FiveM yet.

**Comment by PLOKMJNB** [comment]
Sure! just send a link from gta5-mods.com that looks good

**Comment by gabrielcalderon** [comment]
@PLOKMJNB This is the one with most downloads in gta5-mods. Thanks!

https://www.gta5-mods.com/vehicles/lamborghini-urus-add-on-template

**Comment by PLOKMJNB** [comment]
The Lamborghini Urus has been added! the menu will be updated soon. Feel free to make any more issues!

**Comment by gabrielcalderon** [comment]
Thank you! 😁
