### ISSUE TITLE
Couldn't find resource

### ISSUE THREAD

**Issue by fsjNk** [PLOKMJNB/FiveM-Civ-Car-Pack#11]
Hello, I get this error "Couldn't find resource" and this for every car I did everything, I even completed the vehicle_names.lua.. 
I inserted the cars in my server.cfg and in my DB for my dealership now I started my Server and it can't load any car. 
In my resources I pasted "PLOKS_CARS" folder

**Comment by PLOKMJNB** [comment]
If you're using the latest, I have yet to update all the documents, you only need to add `ensure PLOKS_CARS`. Also if you could PR the finished vehicle_names.lua that would be appreciated

**Comment by fsjNk** [comment]
Oh, thank you very much, I love how organized the pack is 💖
sure I can, only was able to upload it as a .txt file
[vehicle_names.txt](https://github.com/PLOKMJNB/FiveM-Civ-Car-Pack/files/5691524/vehicle_names.txt)

**Comment by PLOKMJNB** [comment]
Are you in the discord? otherwise ill just credit you in the contributor's file

**Comment by fsjNk** [comment]
Yea I just joined, my name is ".avgnd#0001". No need for that, just if you want 😊
I have a .sql file I made for "esx_vehicleshop" so it's possible to buy them there. I just haven't setup every single car price but will do next days. So if you want I can send it too.
