### ISSUE TITLE
Description on GIT

### ISSUE THREAD

**Issue by nvybvl** [PLOKMJNB/FiveM-Civ-Car-Pack#12]
Hello,

This two links overhere are broken.
Note: I used Flatracer's Add-On Menu.

Also can you help us to install the cars on Showrooms / Garages too ?

Thank you

**Comment by PLOKMJNB** [comment]
Could you please explain or indicate what you mean by `This two links overhere are broken.`. Anywho Flatracers menu is going to be replaced with [LondonStudios one](https://github.com/LondonStudios/VehicleSpawner) tomorrow. 

Secondly, I do not use any sort of Garage script but there is someone in the discord who does so, feel free to join and ask, they may provide some assistance.

**Comment by nvybvl** [comment]
> Could you please explain or indicate what you mean by `This two links overhere are broken.`. Anywho Flatracers menu is going to be replaced with [LondonStudios one](https://github.com/LondonStudios/VehicleSpawner) tomorrow.
> 
> Secondly, I do not use any sort of Garage script but there is someone in the discord who does so, feel free to join and ask, they may provide some assistance.

Great, thank you!
