### ISSUE TITLE
Broken Lights and textures

### ISSUE THREAD

**Issue by YonLiud** [PLOKMJNB/FiveM-Civ-Car-Pack#16]
**Mercedes-Benz V-class 250 Bluetec LWB**

The car's front lights and backlights are blue and green, where they should be white and red

**Comment by PLOKMJNB** [comment]
i see that now, ill investigate

https://i.imgur.com/jcU3kX8.jpg | https://i.imgur.com/YmyTz7v.jpg

**Comment by PLOKMJNB** [comment]
I think it may have something to do with the `golfgti7`, try removing the gti's stream and data files and see if the issue persists

**Comment by YonLiud** [comment]
Fixed!
