### ISSUE TITLE
[New Car] Dacia

### ISSUE THREAD

**Issue by nvybvl** [PLOKMJNB/FiveM-Civ-Car-Pack#17]
Let's try to add Dacia to the pack.

**Dacia Duster 2014:** https://www.gta5-mods.com/vehicles/dacia-duster-2014
**Dacia Logan 2008:** https://www.gta5-mods.com/vehicles/2008-dacia-logan
**Dacia Sandero Stepway 2014:** https://www.gta5-mods.com/vehicles/dacia-sandero-stepway-2014
**Dacia Sandero 2014:** https://www.gta5-mods.com/vehicles/dacia-sandero-2014
**Dacia 1310:** https://www.gta5-mods.com/vehicles/dacia-1310
**Dacia Pickup:** https://www.gta5-mods.com/vehicles/dacia-logan-pickup-add-on-unlock

**Comment by DevAnanas0** [comment]
Can´t be done because those Cars are replacements

**Comment by Hamy-os** [comment]
Just… convert them???

**Comment by PLOKMJNB** [comment]
Closed with #57
