### ISSUE TITLE
[Update] Audi

### ISSUE THREAD

**Issue by nvybvl** [PLOKMJNB/FiveM-Civ-Car-Pack#18]
With:
**R8 2020:** https://www.gta5-mods.com/vehicles/audi-r8-2020-addon
**RS6:** https://www.gta5-mods.com/vehicles/2015-audi-rs6-c7-add-on-abt-tuning
**A4:** https://www.gta5-mods.com/vehicles/2017-audi-a4-quattro-abt-replace-tuning

**Comment by PLOKMJNB** [comment]
> R8 2020: https://www.gta5-mods.com/vehicles/audi-r8-2020-addon

https://github.com/PLOKMJNB/FiveM-Civ-Car-Pack/commit/59c7d523018e7ec9bceb5ddad326bd03f6040f18
https://github.com/PLOKMJNB/FiveM-Civ-Car-Pack/commit/f4b9464ec0512b29ad4f4683d8a2c018938d951b

**Comment by PLOKMJNB** [comment]
>RS6: https://www.gta5-mods.com/vehicles/2015-audi-rs6-c7-add-on-abt-tuning
https://github.com/PLOKMJNB/FiveM-Civ-Car-Pack/commit/33194ca987c6c9e5179bd5f0783d2b638c4a4b8f
>A4: https://www.gta5-mods.com/vehicles/2017-audi-a4-quattro-abt-replace-tuning
https://github.com/PLOKMJNB/FiveM-Civ-Car-Pack/commit/b50900b37fdb8477da8d07f524910117438c2f15
