### ISSUE TITLE
[Update] BMW

### ISSUE THREAD

**Issue by nvybvl** [PLOKMJNB/FiveM-Civ-Car-Pack#19]
**i8:** https://www.gta5-mods.com/vehicles/2015-bmw-i8
**x6:** https://www.gta5-mods.com/vehicles/bmw-x6m-f16
**m5:** https://www.gta5-mods.com/vehicles/bmw-m5-f90-2018-add-on-hq-template
**x5:** https://www.gta5-mods.com/vehicles/bmw-x5-e53-2005-sport-package

**Comment by PLOKMJNB** [comment]
Closed with PR #56
