### ISSUE TITLE
Request: Toyota Land Cruiser

### ISSUE THREAD

**Issue by Sl4yers** [PLOKMJNB/FiveM-Civ-Car-Pack#2]
Please sir,
I enjoy your work and support you fully 
i have a request: https://fr.gta5-mods.com/vehicles/toyota-land-cruiser-200-2016

Thank you in advance !

**Comment by PLOKMJNB** [comment]
I have doubts this will work: https://i.imgur.com/IlpOaeZ.png, but I'll try it on my server and let you know

**Comment by PLOKMJNB** [comment]
As I expected it didn't spawn in. I am adding [this](https://www.gta5-mods.com/vehicles/2016-land-cruiser-vxr) in its place. If you find anything else you would like to feel free to make another issue!
