### ISSUE TITLE
[Update] Ford

### ISSUE THREAD

**Issue by nvybvl** [PLOKMJNB/FiveM-Civ-Car-Pack#20]
**Focus RS 2017:** https://www.gta5-mods.com/vehicles/ford-focus-rs-2017-add-on-replace-tuning-template-multi-livery
**Mustang 2015:** https://www.gta5-mods.com/vehicles/2015-ford-mustang-gt
**GT:** https://www.gta5-mods.com/vehicles/2017-ford-gt-add-on-replace-yca-aige
**Mustang Boss 429:** https://www.gta5-mods.com/vehicles/1969-ford-mustang-boss-426

**Comment by PLOKMJNB** [comment]
> GT: https://www.gta5-mods.com/vehicles/2017-ford-gt-add-on-replace-yca-aige

https://github.com/PLOKMJNB/FiveM-Civ-Car-Pack/commit/8e913ed66b8a740b7604ff38f2151a470e5c39b7
