### ISSUE TITLE
[Update] Volkswagen

### ISSUE THREAD

**Issue by nvybvl** [PLOKMJNB/FiveM-Civ-Car-Pack#21]
**Scirocco R 2011:** https://www.gta5-mods.com/vehicles/vw-scirocco-r-2011-beta
**Passat B8:** https://www.gta5-mods.com/vehicles/2016-volkswagen-passat-b8-add-on
**Golf 7 2018:** https://www.gta5-mods.com/vehicles/volkswagen-golf-7-5r-2018-add-on
**Golf 3:** https://www.gta5-mods.com/vehicles/volkswagen-golf-mk3-gti
**Amarok V6:** https://www.gta5-mods.com/vehicles/2018-volkswagen-amarok-v6-add-on-replace

**Comment by PLOKMJNB** [comment]
Closed with PR #56
