### ISSUE TITLE
[Update] Ferrari

### ISSUE THREAD

**Issue by nvybvl** [PLOKMJNB/FiveM-Civ-Car-Pack#22]
**LaFerrari:** https://www.gta5-mods.com/vehicles/2015-ferrari-laferrari-hq-autospoiler
**F12 Berlinetta:** https://www.gta5-mods.com/vehicles/2013-f12-berlinetta
**FXX-K:** https://www.gta5-mods.com/vehicles/ferrari-fxx-k
**488 Spider:** https://www.gta5-mods.com/vehicles/ferrari-488-gts-addon-replace-tuner
**812 Superfast:** https://www.gta5-mods.com/vehicles/ferrari-812-superfast
**California:** https://www.gta5-mods.com/vehicles/ferrari-california-t-2015-replace
**Enzo:** https://www.gta5-mods.com/vehicles/ferrari-enzo-gemballa-mig-u1-tuning-add-on

**For this 6pack just 4 of them:** https://www.gta5-mods.com/vehicles/ferrari-458-spider-2013-add-on-tuning-livery

1. Ferrari 458 Italia
2. Ferrari 458 Speciale
3. Ferrari 458 Spider
4. Ferrari 458 Speciale Aperta

**Comment by PLOKMJNB** [comment]
https://github.com/PLOKMJNB/FiveM-Civ-Car-Pack/commit/454a3e7924a86182db270f3cd5b5fd89d3f74d1d
https://github.com/PLOKMJNB/FiveM-Civ-Car-Pack/commit/07c6d1229d72a354c19094c52ce9c55c7324f8c8
https://github.com/PLOKMJNB/FiveM-Civ-Car-Pack/commit/5bd5b62ea4b9b136b355957f853ebb8a7f5adb17
https://github.com/PLOKMJNB/FiveM-Civ-Car-Pack/commit/10d531511f38f6be273d8a6c1dbd5886ba000e99
https://github.com/PLOKMJNB/FiveM-Civ-Car-Pack/commit/ef7aad66eb1b093e8866ed275229964e094cd0bc
https://github.com/PLOKMJNB/FiveM-Civ-Car-Pack/commit/bfb87d6c0da722fbf548f8682434c2d402e7c5f0
https://github.com/PLOKMJNB/FiveM-Civ-Car-Pack/commit/ae74795aee02ff6dcbe78660a3fc66641e83e50f
