### ISSUE TITLE
request: camaro SS 

### ISSUE THREAD

**Issue by Sl4yers** [PLOKMJNB/FiveM-Civ-Car-Pack#3]
I don't know if you got my last email.
The VXR you converted is fine thank you very much ! 

I have a new request please: 
https://fr.gta5-mods.com/vehicles/1969-chevrolet-camaro-ss-350-aige

**Comment by PLOKMJNB** [comment]
I'll get it done soon!

**Comment by Sl4yers** [comment]
thanks !

Le dim. 7 juin 2020 à 23:11, Danish Khan <notifications@github.com> a
écrit :

**Comment by PLOKMJNB** [comment]
I'm back, and it's now live in the newest update

**Comment by Sl4yers** [comment]
Thank you Danish ! Provenance : Courrier pour Windows 10 De : Danish KhanEnvoyé le :dimanche 19 juillet 2020 22:30À : PLOKMJNB/FiveM-Civ-Car-PackCc : Sl4yers; AuthorObjet :Re: [PLOKMJNB/FiveM-Civ-Car-Pack] request: camaro SS (#3) I'm back, and it's now live in the newest update—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
