### ISSUE TITLE
Corrupted File

### ISSUE THREAD

**Issue by icozyhoodie** [PLOKMJNB/FiveM-Civ-Car-Pack#30]
After download the Car Pack Zip, when I try opening it--it says that the file is corrupted.

**Comment by PLOKMJNB** [comment]
Yes this is a known issue, not sure the source of the issue but, if you follow this guide from the wiki tab, it should work perfectly.

https://github.com/PLOKMJNB/FiveM-Civ-Car-Pack/wiki/VPS-installation

**Comment by Hamy-os** [comment]
I am unable to reproduce this. Follow this for best results: https://github.com/PLOKMJNB/FiveM-Civ-Car-Pack/wiki/VPS-installation
