### ISSUE TITLE
Zip File Corrupt

### ISSUE THREAD

**Issue by LtRevo12** [PLOKMJNB/FiveM-Civ-Car-Pack#34]
Hi, the Zip is corrupt, any help?

**Comment by PLOKMJNB** [comment]
Follow this for best results: https://github.com/PLOKMJNB/FiveM-Civ-Car-Pack/wiki/VPS-installation, other methods seem to be broken

**Comment by LtRevo12** [comment]
Thanks, I will try this and provide feedback

**Comment by LtRevo12** [comment]
Seems to struggle on my side, Any chance that you could re zip the files and upload?

**Comment by PLOKMJNB** [comment]
the pack is a few gigs, it will take a few moments, any case i don't zip it, GitHub automatically does so

**Comment by LtRevo12** [comment]
Ahh I see, so will you be able to repost it?

**Comment by PLOKMJNB** [comment]
I don't post anything, it is all automatic, using the wiki post is the fastest and most stable method
