### ISSUE TITLE
fxversion

### ISSUE THREAD

**Issue by PhxZe** [PLOKMJNB/FiveM-Civ-Car-Pack#35]
When I start my server it says PLOK_CARS does not specify an `fx_version` in fxmanifest.lua.

**Comment by PLOKMJNB** [comment]
This means your server is heavily outdated, I would recommend updating unless you cannot if are using zap or any other GSP, you can find up to date artifacts here: [Windows](https://runtime.fivem.net/artifacts/fivem/build_server_windows/master/?171_fix_cache_3814), [Linux](https://runtime.fivem.net/artifacts/fivem/build_proot_linux/master/?171_fix_cache_3814)

**Comment by PhxZe** [comment]
I have it on a FiveM server with the FivePD add-on. FivePD is up to date what else should I update

**Comment by PLOKMJNB** [comment]
no, Artifacts are your base server files ![](https://beta.iodine.gg/acaea.png) 
These, you need to get an updated version and replace these

**Comment by PhxZe** [comment]
It works now thank you
