### ISSUE TITLE
Can’t Find Resourse (resolved)

### ISSUE THREAD

**Issue by vcmanny** [PLOKMJNB/FiveM-Civ-Car-Pack#36]
hey so I installed like 15 cars and only one worked. I looked in my live console and it says “cant find the resource” for the cars that ain’t work.
![9C1D722A-5999-4929-BBFD-009E8E7B61C8](https://user-images.githubusercontent.com/82255182/114497951-025fb500-9bd8-11eb-8a0d-02a4d0507e87.jpeg)

**Comment by vcmanny** [comment]
@PLOKMJNB i really wanna get those workin, any advice on how to?

**Comment by PLOKMJNB** [comment]
i need to see how you took the files and changed them to make it work

**Comment by vcmanny** [comment]
@PLOKMJNB I didn’t change anything. I just downloaded your pack and inserted the vehicles I wanted into my resourses,my cry, and then into my data base.

**Comment by PLOKMJNB** [comment]
Oh, you don't choose cars, the resource is made to start all at once with `ensure PLOKS_CARS`

**Comment by vcmanny** [comment]
@PLOKMJNB how did the trackhawk work then? I've got most of those cars already I'm just missing those few.

**Comment by PLOKMJNB** [comment]
I myself am unsure why it worked, I've never tried it that way. Just start the entire resource and delete the cars you don't want

**Comment by vcmanny** [comment]
@PLOKMJNB thank you so much. worked great!!!
