### ISSUE TITLE
2005 Ford Mustang GT Mk.V

### ISSUE THREAD

**Issue by LucasOnTop** [PLOKMJNB/FiveM-Civ-Car-Pack#38]
https://www.gta5-mods.com/vehicles/2005-ford-mustang-gt-mk-v Hello, can make that fivem ready and after if you can can you send it to me on discord and put it in the folder my discord is Kieran L.#6969 because i dont want to download the pack again coz it pretty big

**Comment by PLOKMJNB** [comment]
Sure! just join the discord. Once it's been added I can ping you with the zip.

**Comment by Hamy-os** [comment]
Done, pr as soon as repo finishes cloning. Here is the zip
[mustang2005gt.zip](https://github.com/PLOKMJNB/FiveM-Civ-Car-Pack/files/7230239/mustang2005gt.zip)

**Comment by Hamy-os** [comment]
added in e838acf @PLOKMJNB you can close this
