### ISSUE TITLE
Adding .sql file for esx_vehicleshop

### ISSUE THREAD

**Issue by Elkaa0** [PLOKMJNB/FiveM-Civ-Car-Pack#39]
Hello, I really appreciate what are you doing if you have a reading .sql file to add vehicles into the esx_vehcile shop under a category named imports it's gonna be perfectttt :D

**Comment by PLOKMJNB** [comment]
If you join the discord, there is a slightly outdated .SQL file in the general chat, I don't use esx or any framework so I don't maintain any but I may in the future include one.

**Comment by YonLiud** [comment]
check this PR, it has not been accepted yet but seems to be good enough for you!

#46
