### ISSUE TITLE
[request]JDM Rims

### ISSUE THREAD

**Issue by Sl4yers** [PLOKMJNB/FiveM-Civ-Car-Pack#4]
Hi,

Can you help me with these rims ? how to make them work in Lscustom menu ? 
Can you convert this to work with right _resource please ?

Thank you 

https://www.gta5-mods.com/vehicles/jdm-rims-pack

**Comment by PLOKMJNB** [comment]
Hey, Sorry I've been busy but I'll look and implement these rims into the pack. Not sure how these will interact with a LS Customs plug-in for ESX, but I'll investigate

**Comment by PLOKMJNB** [comment]
Also you still want that Avant?

**Comment by Sl4yers** [comment]
hey!

No problem mate, take your time if you are busy !
wanted to ask if you have a complete base and database, even for sell ?
working and functional

I managed to make the RS6 avant work but thanks !

Le dim. 21 juin 2020 à 22:58, Danish Khan <notifications@github.com> a
écrit :

**Comment by PLOKMJNB** [comment]
DM me on discord PLOKMJNB#8692

**Comment by PLOKMJNB** [comment]
The rims are currently working, just not sure how to get to them. Need to see how to get them on cars.

**Comment by Sl4yers** [comment]
I managed to make them work by adding them one by one in the carcols.lua of
a random import vehicle. Then it appears in lscustoms for every car
but I dont know how to make the pack work as a whole.

Le lun. 29 juin 2020 à 17:11, Danish Khan <notifications@github.com> a
écrit :
