### ISSUE TITLE
New Vehicle

### ISSUE THREAD

**Issue by ElBrigos** [PLOKMJNB/FiveM-Civ-Car-Pack#42]
Hey thx for your work ! i give you a list of véhicle to add it ^^

Peugeot - 205 turbo 16
https://fr.gta5-mods.com/vehicles/peugeot-205-turbo-16-rally-2in1-add-on-tuning-livery

Peugeot - 205 Rallye
https://fr.gta5-mods.com/vehicles/1991-peugeot-205-rallye

Renault - Twingo
https://fr.gta5-mods.com/vehicles/renault-twingo-i

Volkswagen - Golf 8 GTI (new 2022)
https://fr.gta5-mods.com/vehicles/volkswagen-golf-8-gti-unlocked-add-on

**Comment by PLOKMJNB** [comment]
Closed with #57
