### ISSUE TITLE
Incorrect installation guide

### ISSUE THREAD

**Issue by YonLiud** [PLOKMJNB/FiveM-Civ-Car-Pack#44]
## Issue

Guide does not mention export of `PLOK_CARS/` on [This Page](https://github.com/PLOKMJNB/FiveM-Civ-Car-Pack/wiki/VPS-installation)

## Solution

Remove these lines:
1) ~~` To save space you can delete the following files/directory's `~~ 
2) ~~` NOTE: if you do not plan on using the Vehicle Spawner you can delete that folder as well `~~

And replace with:
 1) `` Export PLOK_CARS directory to `resources` folder ``
 2) `` **NOTE:** Add `VehicleSpawner` folder to `resources` folder if you plan to use it as well ``

**Comment by PLOKMJNB** [comment]
[Updated](https://github.com/PLOKMJNB/FiveM-Civ-Car-Pack/wiki/VPS-installation/b904a27bdabb847f0704aa4b836422342ee69cb3)
