### ISSUE TITLE
Cars to add plz toyota-trueno-ae86

### ISSUE THREAD

**Issue by Insaneshane99** [PLOKMJNB/FiveM-Civ-Car-Pack#47]
https://www.gta5-mods.com/vehicles/toyota-trueno-ae86-add-on-rhd-lnital-d

https://www.gta5-mods.com/vehicles/1983-toyota-sprinter-trueno-3door-1600gt-apex-ae86

**Comment by PLOKMJNB** [comment]
Closed with PR #56
