### ISSUE TITLE
Charger problem

### ISSUE THREAD

**Issue by OGRakoon** [PLOKMJNB/FiveM-Civ-Car-Pack#48]
I’m having a problem with the SRT 2020 Charger Widebody where it is not making engine sounds or any noise at all 

if someone can help, that’ll be much appreciated 

Thanks 🙂

**Comment by PLOKMJNB** [comment]
PR coming soon

**Comment by Hamy-os** [comment]
is this still an issue?

**Comment by P4R4NORM4L** [comment]
probably same issue as supra where audio hash cannot be found therefore no sound just change the line audio hash to a vehicle which is in the game like ASEA and it should work

**Comment by P4R4NORM4L** [comment]
Added a pull request to fix this issue if it gets merged, When it get's merged, all you need to do is replace the vehicles.meta file of the updated one to the one you have in your server.
