### ISSUE TITLE
Cars are slow to load in

### ISSUE THREAD

**Issue by sparkling-source** [PLOKMJNB/FiveM-Civ-Car-Pack#50]
Vehicles take forever to load in if vMenu is used.

**Comment by YonLiud** [comment]
The issue seems to be with the server.
The streaming of vehicles has nothing to do with the pack itself!

Try optimizing your server or getting a faster server

**Comment by sparkling-source** [comment]
> The issue seems to be with the server.
> The streaming of vehicles has nothing to do with the pack itself!
> 
> Try optimizing your server or getting a faster server

Thank you!
