### ISSUE TITLE
SQL file not working / with sollution.

### ISSUE THREAD

**Issue by Brutuss** [PLOKMJNB/FiveM-Civ-Car-Pack#51]
Hi, first nice car pack!! The SQL file for importing al cars doesn't work you need to change the following lines at the bottom:

From:
	("W-Motors Fenyr Supersport","wmfenyr",220000,"wmotors"),
	("W-Motors Lykan HyperSport","lykan",185000,"wmotors"),
;

To:
	("W-Motors Fenyr Supersport","wmfenyr",220000,"wmotors"),
	("W-Motors Lykan HyperSport","lykan",185000,"wmotors")

Greetings.

**Comment by PLOKMJNB** [comment]
Fixed with #53
