### ISSUE TITLE
List of vehicle and related issues

### ISSUE THREAD

**Issue by Log-nx** [PLOKMJNB/FiveM-Civ-Car-Pack#62]
Below is a list of issues after going through the cars, I went through the vehicles on 2 different frameworks with same issue. 
(ESX & QB) 

Teslax - Unrealistic Speed (can be changed via meta but putting here in case you would like to adjust) 
golf8gti - No Vehicle Sound
Dragekcivic - Crashes user
X6M - Doesnt Spawn
2015 Tahoe - Change to Realistic Sound
Tesla Roadster - Handling Needs Major Looking at | Speed Unrealistic | Breaking | Handling (can be changed via meta but putting here in case you would like to adjust) 
1998 Nissan Silvia S14
2020 Charger chr20 - No Sound
Ferrari F12 & F60 Doesnt Load
1998 Toyota Supra - No Sound
2017 720S - Sound Issues
GSX19 - Doesnt load

**Comment by strongprincess** [comment]
the wraith nor dawnoynx spawn

**Comment by PLOKMJNB** [comment]
> Below is a list of issues after going through the cars, I went through the vehicles on 2 different frameworks with same issue. 
> (ESX & QB) 
> 
> Teslax - Unrealistic Speed (can be changed via meta but putting here in case you would like to adjust) 
> golf8gti - No Vehicle Sound
> Dragekcivic - Crashes user
> X6M - Doesnt Spawn
> 2015 Tahoe - Change to Realistic Sound
> Tesla Roadster - Handling Needs Major Looking at | Speed Unrealistic | Breaking | Handling (can be changed via meta but putting here in case you would like to adjust) 
> 1998 Nissan Silvia S14
> 2020 Charger chr20 - No Sound
> Ferrari F12 & F60 Doesnt Load
> 1998 Toyota Supra - No Sound
> 2017 720S - Sound Issues
> GSX19 - Doesnt load

A few of these were reported but thank you for an entire list for me to start looking into!

**Comment by PLOKMJNB** [comment]
> the wraith nor dawnoynx spawn
> 

I run the pack on the own personal servers and have tested those cars; they seem to work just fine. PLease ensure your download of the repo is up-to-date or try re-downloading and ensuring the pack

**Comment by Hamy-os** [comment]
so what is the final list of stuff that needs fixing?

**Comment by strongprincess** [comment]
thanks i got mine working as the stream folder wasn't being read my bad and thank you for replying

**Comment by Hamy-os** [comment]
> thanks i got mine working as the stream folder wasn't being read my bad and thank you for replying

nice but as to the original topic are all the issues valid?

**Comment by Log-nx** [comment]
> > thanks i got mine working as the stream folder wasn't being read my bad and thank you for replying
> 
> nice but as to the original topic are all the issues valid?

Issues are still valid on my end if anyone else is having this issue im not sure of however. 

> > the wraith nor dawnoynx spawn
> 
> I run the pack on the own personal servers and have tested those cars; they seem to work just fine. PLease ensure your download of the repo is up-to-date or try re-downloading and ensuring the pack


I can confirm I downloaded via git when downloading the vehicle pack. (using the git bash way) I can attempt to pull them again and see if any changes.

**Comment by Log-nx** [comment]
After pulling the git again it seems the above cars were fixed, below is what was left that wasn't working I went ahead and provided some of those fixes only 1 (GSX19) which is the bike has the texture issues. 

**golf8gti - No vehicle sound (However below is the fix)**
_in vehicles.meta you are missing the audoNameHash below is the fixed line._
`<audioNameHash>carbonizzare</audioNameHash>`

**Dragekcivic - Crashes user**
 _(Seems to have fixed itself could be shader related issue)_

**1998 Toyota Supra - No Sound (Below is fix)**
_in vehicles.meta you are using a invalid name in the audoNameHash below is the fixed line._
`<audioNameHash>carbonizzare</audioNameHash>`

**GSX19 - Doesnt load (Textures are way weird missing tires)**
![image](https://user-images.githubusercontent.com/40924447/134788731-c00994ee-8227-4bc9-8a88-a422c625b499.png)

**Comment by Hamy-os** [comment]
> golf8gti - No vehicle sound (However below is the fix)
in vehicles.meta you are missing the audioNameHash below is the fixed line.
<audioNameHash>carbonizzare</audioNameHash>

> 1998 Toyota Supra - No Sound (Below is fix)
in vehicles.meta you are using a invalid name in the audioNameHash below is the fixed line.
<audioNameHash>carbonizzare</audioNameHash>

thank you these have been fixed in an upcoming pr looking into the bike now

**Comment by Hamy-os** [comment]
bike fixed in 
d950e71

**Comment by Hamy-os** [comment]
@PLOKMJNB close please
