### ISSUE TITLE
toysupmk4 Issu

### ISSUE THREAD

**Issue by Kibadeer** [PLOKMJNB/FiveM-Civ-Car-Pack#65]
I try out the Toyota Subra MK4 there is no car sound and no upgrades. Can someone help me with that?

**Comment by P4R4NORM4L** [comment]
First you would need to change the wheel type then go back to front wheel to change the wheels, it's not by just changing the type only that you will see a difference. If you change the Wheel type, it will always revert to the default wheel
1st - Change wheel type
2nd - Change actual wheel
 It works for me and sometimes the mods take sometime to load in, but it looks like they all work. 
 
![image](https://user-images.githubusercontent.com/17122685/138148764-28d9e4fe-40d1-4a86-8c79-f76929dc6176.png)
![image](https://user-images.githubusercontent.com/17122685/138148804-d59b0a0a-42f2-4ea9-9f1a-bd2a96b4f4c4.png)

**Comment by Kibadeer** [comment]
![Bild_2021-10-20_203755](https://user-images.githubusercontent.com/76842680/138151881-283ea117-766d-493f-91cc-7090b16603ba.png)
Here for me its complet empty and dosnt work at all but the car sound works now

**Comment by P4R4NORM4L** [comment]
im on ploks discord i can answer in there faster if you want

**Comment by Kibadeer** [comment]
> im on ploks discord i can answer in there faster if you want
im in
