### ISSUE TITLE
Polk

### ISSUE THREAD

**Issue by t0es4121** [PLOKMJNB/FiveM-Civ-Car-Pack#7]
Sorry Im not familiar with git up other wise I would of found another way to contact you @PLOKMJNB , Could i have your permission to post your pack on forums.cfx.re as a single resource pack? I have had your pack on my server for a while now and decided that 100+ resources was to much so I made a pack that i am looking to release.

**Comment by PLOKMJNB** [comment]
Well Hi there! I am in the process of adding about 30 or so cars and making it one resource as well but go ahead!

**Comment by PLOKMJNB** [comment]
Also make sure to join the [discord](https://discord.gg/vZmRp7EqSS) so we can communicate faster

**Comment by t0es4121** [comment]
ok thanks!

**Comment by PLOKMJNB** [comment]
Did you ever get around to it?

**Comment by xDope7137** [comment]
I don't think FiveM allows you to release anything that is not made by you. You need to get permission from each of the authors of vehicle to compile them and then you can release them

**Comment by PLOKMJNB** [comment]
Yea, im gonna close this. Seems like a dead end
