### ISSUE TITLE
SQL import

### ISSUE THREAD

**Issue by Sopherl81** [PLOKMJNB/FiveM-Civ-Car-Pack#70]
How can I Import the SQL File to the Database. I get an error the vehicels not exist.

**Comment by DevAnanas0** [comment]
https://www.youtube.com/watch?v=jW5lrS6EUPM

**Comment by Sopherl81** [comment]
I know how to Import it. There is a error Massage when I Import it.

**Comment by DevAnanas0** [comment]
Can you send a screenshot?

**Comment by Sopherl81** [comment]
![Snag_14e0aa](https://user-images.githubusercontent.com/42674213/144425373-bda3da65-6440-4578-bdc6-64aa71cd0352.png)

**Comment by DevAnanas0** [comment]
You don´t have a Table with vehicle categories what carshop are you using?

**Comment by Sopherl81** [comment]
Thanks!

That was my error... I changed to advanced vehicle Shop and forgot it...
