### ISSUE TITLE
No BMW x6m on stream folder

### ISSUE THREAD

**Issue by krygx** [PLOKMJNB/FiveM-Civ-Car-Pack#73]
![image](https://user-images.githubusercontent.com/96379733/146679145-172245e9-03df-4ddd-9b30-0c75c6920a2d.png)

**Comment by PLOKMJNB** [comment]
Fixed issue with https://github.com/PLOKMJNB/FiveM-Civ-Car-Pack/commit/d4c70a17e825335401e7c6228a08b52305e430bb
