### ISSUE TITLE
2017 Raptor Issue

### ISSUE THREAD

**Issue by DevilDonkey69** [PLOKMJNB/FiveM-Civ-Car-Pack#75]
The 2017 Raptor (raptor2017) does not spawn into the game.
I verified that all names match up in each file, which they all do appear to; and it does not spawn in.

**Comment by QuarterMileRP** [comment]
I encountered the same issue. When I looked, there were no .ytd's or .ydd in the stream folder for that vehicle.. All in all a great pack... Thanx for that!

**Comment by PLOKMJNB** [comment]
Fixed with https://github.com/PLOKMJNB/FiveM-Civ-Car-Pack/commit/f191fd0f85b560651d6d05080fb926f103542bff
