### ISSUE TITLE
rar problem

### ISSUE THREAD

**Issue by Kyacx** [PLOKMJNB/FiveM-Civ-Car-Pack#79]
Am I the only one that cant extract the rar because of the following problem?
[https://prnt.sc/ttZoLqBlhzBi
![image_2022-05-11_200036149](https://user-images.githubusercontent.com/48531014/167906159-4c9decfb-7a25-41cb-9626-d2f705fdc080.png)
](url)

**Comment by IamFenixDesign** [comment]
What i do to fix this is just download the Github app an make a Clone of the source in the app

**Comment by PLOKMJNB** [comment]
https://github.com/PLOKMJNB/FiveM-Civ-Car-Pack/wiki/VPS-installation
