### ISSUE TITLE
qbcore vehicle.lua

### ISSUE THREAD

**Issue by PLU12** [PLOKMJNB/FiveM-Civ-Car-Pack#89]
make it so there is a vehicle.lua file with all of the cars for qbcore framework

**Comment by gusxyz** [comment]
ima  do it and make a pr

**Comment by BadBraddA1** [comment]
Me and my team made one. I'll go get it and drop a link

**Comment by BadBraddA1** [comment]
PLOKS_CARS/shared.lua is the file you want. Just copy the code and put in the vehicle.lua https://github.com/PLOKMJNB/FiveM-Civ-Car-Pack/blob/175c4fe856d537e33f335de8576727328b4ff5eb/PLOKS_CARS/shared.lua
